[workspace]
channels = ["conda-forge"]
name = "actin_projet"
platforms = [
  "linux-64",
  "linux-aarch64",
  "osx-64",
  "osx-arm64"
]
version = "0.1.0"

[tasks]

[dependencies]
streamlit = ">=1.54.0,<2"
lxml = ">=6.0.2,<7"
html5lib = ">=1.1,<2"
beautifulsoup4 = ">=4.14.3,<5"
jupyterlab = ">=4.5.5,<5"
ipykernel = ">=7.2.0,<8"
