"""Comparison of ABP interface motifs with FoldDisco.

Provides, per PAIR of ABPs at a site, the "same interface motif" verdict + the
FoldDisco score. These columns are merged into the "Pairwise comparison of the
site's ABPs" table (streamlit._render_cluster_struct) — a single table.

Data: data/exports/abp_site_domain/folddisco_interface.csv
(generated by script/abp_site_domain/13_folddisco_interface.py).
"""
import os
import pandas as pd
import streamlit as st
import plotly.graph_objects as go

_FD_CSV = "data/exports/abp_site_domain/folddisco_interface.csv"
_DISCO_CSV = "data/exports/abp_site_domain/folddisco_discovery.csv"

# No binary "same motif" verdict: the raw FoldDisco score has no absolute scale
# and no threshold cleanly separates the distributions (strong overlap between
# same-family / different-family). So we expose the values and let the reader
# judge: score_norm (quality, 0-1) + % shared motif (coverage).


def _reading(n_used, frac, sn, rmsd):
    """GRADED reading (a guide, not a verdict) combining the 4 FoldDisco signals:
    coverage (frac), geometric quality (score_norm), fidelity (RMSD) and
    number of residues (robustness). A low RMSD on few residues is not
    conclusive; high coverage with high RMSD = shared but loose."""
    if n_used is None or frac is None:
        return "—"
    if n_used < 5:
        return "few residues — inconclusive"
    _tight = rmsd is not None and rmsd <= 4          # tight superposition
    _loose = rmsd is not None and rmsd > 6           # loose superposition
    if frac >= 0.75 and _tight and (sn or 0) >= 0.15:
        return "same motif (strong)"
    if frac >= 0.75:                                 # well covered but not tight
        return "residues largely shared, loose superposition"
    if frac >= 0.50:
        return "partially shared motif"
    return "different motifs"


@st.cache_data(show_spinner=False)
def _load_folddisco(_mtime):
    if not os.path.exists(_FD_CSV):
        return None
    return pd.read_csv(_FD_CSV)


def folddisco_pair_map(abps):
    """Returns {frozenset({A,B}): {FoldDisco columns}} for the given ABPs.

    None if FoldDisco not computed; {} if no pair. All values come from
    a SINGLE hit (the smaller motif searched in the other), so they are consistent.
    Columns = raw `folddisco query` outputs + normalised versions:
      * 'Matched residues' = n_match / size of the queried motif (raw)
      * '% shared motif'   = n_match / size (coverage, %)
      * 'FoldDisco score'  = raw score (rarity, no absolute scale)
      * 'Norm. score'      = score / self-match (0-1 = geometric quality)
      * 'RMSD (Å)'         = superposition of matched residues (low = true
                             3D overlap; note: trivially low if few residues).
    """
    mt = os.path.getmtime(_FD_CSV) if os.path.exists(_FD_CSV) else 0.0
    df = _load_folddisco(mt)
    if df is None:
        return None
    aset = set(abps)
    sub = df[df["query_abp"].isin(aset) & df["target_abp"].isin(aset)
             & (~df["self"])].copy()
    if sub.empty:
        return {}
    # ACTUAL motif size of each ABP = number of contact residues (query_size)
    qsize = (df.drop_duplicates("query_abp")
             .set_index("query_abp")["query_size"].to_dict())
    sub["pair"] = sub.apply(
        lambda r: frozenset((r["query_abp"], r["target_abp"])), axis=1)
    out = {}
    for pair, g in sub.groupby("pair"):
        a, b = tuple(pair)
        # ONE direction of comparison so the 4 columns are consistent:
        # "is the SMALLER of the two motifs found in the other?" (the most
        # stringent). All values come from THIS hit — score, score_norm,
        # coverage and RMSD describe the same match.
        sa, sb = qsize.get(a), qsize.get(b)
        small = a if (sa or 1e9) <= (sb or 1e9) else b
        rsmall = g[g["query_abp"] == small]
        _hit = rsmall.iloc[0] if len(rsmall) else g.loc[g["score"].idxmax()]
        _qsz = qsize.get(_hit["query_abp"])
        n_used = int(_hit["n_match"])
        frac = n_used / _qsz if _qsz else None
        sn = pd.to_numeric(_hit.get("score_norm"), errors="coerce")
        _rmsd = pd.to_numeric(_hit.get("rmsd"), errors="coerce")
        _snv = float(sn) if pd.notna(sn) else None
        _rmv = float(_rmsd) if pd.notna(_rmsd) else None
        out[pair] = {
            # raw FoldDisco outputs (query -> target) + normalised versions
            "Matched residues": (f"{n_used}/{_qsz}" if _qsz else str(n_used)),  # n_match
            "% shared motif": (f"{round(frac * 100)}%" if frac is not None else "—"),
            "FoldDisco score": round(float(_hit["score"]), 1),                  # score brut
            "Norm. score": round(_snv, 2) if _snv is not None else None,        # score/self
            "RMSD (Å)": round(_rmv, 1) if _rmv is not None else None,           # rmsd
            "Interpretation": _reading(n_used, frac, _snv, _rmv),
        }
    return out


# ── DISCOVERY: interface motif (per ABP × cluster) searched in PDB + AlphaFold ─
# discovery CSV (script 14)  : db, target_id, target_chain, idfscore, rmsd, coverage…
# names CSV (script 14b)      : key, protein_name, organism  (UniProt / RCSB)
# We show the protein NAME (not the raw id), deduplicate by name, 2 tabs.

_DISCO_NAMES = "data/exports/abp_site_domain/folddisco_names.csv"
_DB_TABS = [("pdb", "PDB (real structures)"),
            ("afdb", "AlphaFold (predictions)")]

# Filter on the interpretation (same categories as _reading, the local FoldDisco).
_FILTERS = {
    "Same motif (strong) only": {"same motif (strong)"},
    "Same motif + shared (broad/partial)": {
        "same motif (strong)",
        "residues largely shared, loose superposition",
        "partially shared motif"},
    "All": None,
}
_INTERP_COL = {
    "same motif (strong)": "#1a7f37",
    "residues largely shared, loose superposition": "#9a6700",
    "partially shared motif": "#9a6700",
    "different motifs": "#8c8c8c",
    "few residues — inconclusive": "#8c8c8c",
}


@st.cache_data(show_spinner=False)
def _load_discovery(_mtime):
    if not os.path.exists(_DISCO_CSV):
        return None
    df = pd.read_csv(_DISCO_CSV)
    # join resolved names (if available)
    if os.path.exists(_DISCO_NAMES):
        nm = pd.read_csv(_DISCO_NAMES)[["key", "protein_name", "organism"]]
        df["key"] = [t if d == "afdb" else f"{t}_{c}" for d, t, c
                     in zip(df["db"], df["target_id"],
                            df["target_chain"].fillna(""))]
        df = df.merge(nm, on="key", how="left")
    else:
        df["protein_name"] = None
        df["organism"] = None
    df["name"] = df["protein_name"].fillna("").replace("", pd.NA)
    df["name"] = df["name"].fillna(df["target_id"])      # fallback = raw id
    # normalised score: ÷ the self-match (self, is_source) of each query×db;
    # otherwise (ABP absent from db) ÷ the group's best hit → comparable 0-1.
    keys = ["query_abp", "query_cluster", "db"]
    self_s = df[df["is_source"]].groupby(keys)["idfscore"].max()
    grp_s = df.groupby(keys)["idfscore"].max()
    den = self_s.reindex(grp_s.index).fillna(grp_s).rename("_den")
    df = df.merge(den, on=keys, how="left")
    df["score_norm"] = (df["idfscore"] / df["_den"]).round(3)
    # graded interpretation (same rules as the local FoldDisco, see _reading)
    df["interpretation"] = [
        _reading(n, c, s, r) for n, c, s, r in
        zip(df["nodecount"], df["coverage"], df["score_norm"], df["rmsd"])]
    return df


def _hit_link(db, tid):
    return (f"https://www.rcsb.org/structure/{tid.upper()}" if db == "pdb"
            else f"https://alphafold.ebi.ac.uk/entry/{tid}")


def _dedup_by_name(sub):
    """One row per protein NAME (best score), sorted by descending score."""
    return sub.sort_values("idfscore", ascending=False).drop_duplicates("name")


def _interp_filter_ui(key):
    """Filter radio; default = 'same motif (strong)' (strict)."""
    return st.radio("Keep only", list(_FILTERS), index=0, horizontal=True,
                    key=key)


def _hbar(names, scores, colors=None):
    """HORIZONTAL bar chart (full readable names), best on top."""
    fig = go.Figure(go.Bar(
        x=list(scores), y=list(names), orientation="h",
        marker_color=colors or "#3b6fb5"))
    fig.update_layout(
        height=max(220, 26 * len(names) + 60),
        margin=dict(l=6, r=6, t=6, b=6),
        xaxis_title="Normalised score (÷ self-match)",
        yaxis=dict(autorange="reversed"))
    st.plotly_chart(fig, use_container_width=True)


def _render_db_table(sub, db, filt):
    """Table + chart for one db (sub already filtered db + non-source + names)."""
    d = _dedup_by_name(sub).copy()
    keep = _FILTERS[filt]
    if keep is not None:
        d = d[d["interpretation"].isin(keep)]
    if d.empty:
        st.caption("No protein at this similarity level.")
        return
    d["Source"] = (d["target_id"].str.upper()
                   + (" / " + d["target_chain"].fillna("") if db == "pdb" else ""))
    d["Norm. score"] = d["score_norm"].round(2)
    d["RMSD (Å)"] = d["rmsd"].round(2)
    d["Coverage"] = (d["coverage"] * 100).round().astype("Int64").astype(str) + "%"
    cols = ["name", "organism", "interpretation", "Norm. score", "RMSD (Å)",
            "Coverage", "Source"]
    show = d[cols].rename(columns={"name": "Protein", "organism": "Organism",
                                   "interpretation": "Interpretation"})
    st.caption(f"{len(d)} distinct proteins")
    st.dataframe(
        show, hide_index=True, use_container_width=True, height=400,
        column_config={
            "Protein": st.column_config.TextColumn(width="large"),
            "Organism": st.column_config.TextColumn(width="medium")})
    top = d.head(15)
    _hbar(top["name"], top["score_norm"],
          [_INTERP_COL.get(i, "#3b6fb5") for i in top["interpretation"]])


def render_discovery(sel_abp):
    """Per-ABP view, broken down by cluster: one motif per site, 2 dbs (PDB/AFDB)."""
    st.subheader("Discovery — interface motif per cluster (FoldDisco)")
    mt = os.path.getmtime(_DISCO_CSV) if os.path.exists(_DISCO_CSV) else 0.0
    df = _load_discovery(mt)
    if df is None:
        st.caption(
            "Not computed. Run `14_folddisco_discovery.py` then "
            "`14b_resolve_names.py` (PDB + AlphaFold search, one motif per "
            "ABP × cluster, resolved names).")
        return
    abp = df[df["query_abp"] == sel_abp]
    if abp.empty:
        st.info("No discovery result for this ABP (not computed yet).")
        return
    clusters = sorted(abp["query_cluster"].unique())
    cl = st.selectbox(
        f"Actin site of {sel_abp} ({len(clusters)} cluster(s) → as many motifs)",
        clusters, key=f"disco_cl_{sel_abp}")
    filt = _interp_filter_ui(f"disco_filt_{sel_abp}_{cl}")
    sub = abp[(abp["query_cluster"] == cl) & (~abp["is_source"])]
    tabs = st.tabs([lbl for _, lbl in _DB_TABS])
    for tab, (db, _) in zip(tabs, _DB_TABS):
        with tab:
            _render_db_table(sub[sub["db"] == db], db, filt)
    st.caption(
        f"Interface motif of **{sel_abp}** at site **{cl}** searched in the **PDB** "
        "(real structures → protein = the complex chain) and the **AlphaFold "
        "proteome** (1 predicted protein per hit, often in other species). "
        "**Interpretation** (same rules as the local FoldDisco, combines coverage / "
        "RMSD / normalised score): *same motif (strong)* = coverage ≥ 75 % + RMSD ≤ 4 Å "
        "+ norm. score ≥ 0.15 · *loose shared* = well covered but RMSD > 4 · *partial* "
        "= coverage ≥ 50 % · *different* otherwise · *inconclusive* < 5 residues. "
        "**Norm. score** = score ÷ self-match (0-1, comparable) — the raw score "
        "has no absolute scale. Deduplicated by name, source excluded.")


def render_discovery_cluster(cluster_id):
    """Per-CLUSTER view — pools the discoveries of ALL the site's ABPs,
    deduplicated by name. # ABPs > 1 = strong convergence toward this site."""
    st.markdown("**Discovery — proteins matching this site's motif (FoldDisco)**")
    mt = os.path.getmtime(_DISCO_CSV) if os.path.exists(_DISCO_CSV) else 0.0
    df = _load_discovery(mt)
    if df is None:
        st.caption("Not computed (scripts 14 / 14b).")
        return
    base = df[(df["query_cluster"] == cluster_id) & (~df["is_source"])]
    if base.empty:
        st.caption("No discovery for this site (not computed yet).")
        return
    filt = _interp_filter_ui(f"disco_clfilt_{cluster_id}")
    keep = _FILTERS[filt]
    tabs = st.tabs([lbl for _, lbl in _DB_TABS])
    for tab, (db, _) in zip(tabs, _DB_TABS):
        with tab:
            sub = base[base["db"] == db]
            if keep is not None:
                sub = sub[sub["interpretation"].isin(keep)]
            if sub.empty:
                st.caption("No protein at this similarity level.")
                continue
            rows = []
            for nom, g in sub.groupby("name"):
                best = g.loc[g["idfscore"].idxmax()]
                rows.append({
                    "Protein": nom,
                    "Organism": best.get("organism", ""),
                    "Interpretation": best["interpretation"],
                    "Found via (ABP)": ", ".join(sorted(g["query_abp"].unique())),
                    "# ABPs": g["query_abp"].nunique(),
                    "Norm. score": round(float(best["score_norm"]), 2),
                    "RMSD (Å)": round(float(best["rmsd"]), 2),
                    "Link": _hit_link(db, best["target_id"]),
                })
            out = pd.DataFrame(rows).sort_values(
                ["# ABPs", "Norm. score"], ascending=[False, False])
            st.caption(f"{len(out)} distinct proteins · "
                       f"{(out['# ABPs'] > 1).sum()} via several ABPs")
            st.dataframe(
                out, hide_index=True, use_container_width=True, height=400,
                column_config={
                    "Protein": st.column_config.TextColumn(width="large"),
                    "Link": st.column_config.LinkColumn("Fiche",
                                                        display_text="ouvrir")})
    st.caption(
        "Interface motifs of **all the ABPs at this site** (PDB + AlphaFold), "
        "**pooled and deduplicated by name**. **# ABPs** = how many different "
        "ABPs this protein came up through: **> 1 = strong convergence**. "
        "**Interpretation** = same graded reading as the per-ABP view. Sources excluded.")
