from display_helpers import plotly_chart
"""Comparison of ABP interface motifs with FoldDisco.

Provides saved pairwise scores, auditable discovery coverage, and local query
inspection/preparation. Prepared queries never alter or recalculate saved hits.

Data: data/exports/abp_site_domain/folddisco_interface.csv
(generated by script/abp_site_domain/13_folddisco_interface.py).
"""
import os
from pathlib import Path
import pandas as pd
import streamlit as st
import plotly.graph_objects as go
from folddisco_audit import (CATALOG_FILES, EXPORTS, motif_catalog, coverage_tables,
                            normalize_discovery, structure_path, read_chain_ca,
                            validate_motif, prepared_query_json)

_FD_CSV = "data/exports/abp_site_domain/folddisco_interface.csv"
_DISCO_CSV = "data/exports/abp_site_domain/folddisco_discovery.csv"

# No binary "same motif" verdict: the raw FoldDisco score has no absolute scale
# and no threshold cleanly separates the distributions (strong overlap between
# same-family / different-family). So we expose the values and let the reader
# judge: score_norm (a source-relative ratio) + % shared motif (coverage).


def _reading(n_used, frac, sn, rmsd):
    """GRADED reading (a guide, not a verdict) combining the 4 FoldDisco signals:
    coverage (frac), geometric quality (score_norm), fidelity (RMSD) and
    number of residues (robustness). A low RMSD on few residues is not
    conclusive; high coverage with high RMSD = shared but loose."""
    if n_used is None or frac is None or pd.isna(n_used) or pd.isna(frac):
        return "missing metrics — unclassified"
    if n_used < 5:
        return "few residues — inconclusive"
    _tight = rmsd is not None and rmsd <= 4          # tight superposition
    _loose = rmsd is not None and rmsd > 6           # loose superposition
    if frac >= 0.75 and _tight and (sn or 0) >= 0.15:
        return "same motif (strong)"
    if frac >= 0.75:                                 # well covered but not tight
        return "residues largely shared, loose superposition"
    if frac >= 0.50:
        return "partially shared motif"
    return "different motifs"


@st.cache_data(show_spinner=False)
def _load_folddisco(mtime):
    if not os.path.exists(_FD_CSV):
        return None
    return pd.read_csv(_FD_CSV)


def folddisco_pair_map(abps):
    """Returns {frozenset({A,B}): {FoldDisco columns}} for the given ABPs.

    None if FoldDisco not computed; {} if no pair. All values come from
    a SINGLE hit (the smaller motif searched in the other), so they are consistent.
    Columns = raw `folddisco query` outputs + normalised versions:
      * 'Matched residues' = n_match / size of the queried motif (raw)
      * '% shared motif'   = n_match / size (coverage, %)
      * 'FoldDisco score'  = raw score (rarity, no absolute scale)
      * 'Norm. score'      = score / self-match (a ratio, not a calibrated quality)
      * 'RMSD (Å)'         = superposition of matched residues (low = true
                             3D overlap; note: trivially low if few residues).
    """
    mt = os.path.getmtime(_FD_CSV) if os.path.exists(_FD_CSV) else 0.0
    df = _load_folddisco(mt)
    if df is None:
        return None
    aset = set(abps)
    sub = df[df["query_abp"].isin(aset) & df["target_abp"].isin(aset)
             & (~df["self"])].copy()
    if sub.empty:
        return {}
    # ACTUAL motif size of each ABP = number of contact residues (query_size)
    qsize = (df.drop_duplicates("query_abp")
             .set_index("query_abp")["query_size"].to_dict())
    sub["pair"] = sub.apply(
        lambda r: frozenset((r["query_abp"], r["target_abp"])), axis=1)
    out = {}
    for pair, g in sub.groupby("pair"):
        a, b = sorted(pair)
        # ONE direction of comparison so the 4 columns are consistent:
        # "is the SMALLER of the two motifs found in the other?" (the most
        # stringent). All values come from THIS hit — score, score_norm,
        # coverage and RMSD describe the same match.
        sa, sb = qsize.get(a), qsize.get(b)
        small = a if (sa or 1e9) <= (sb or 1e9) else b
        rsmall = g[g["query_abp"] == small]
        _hit = rsmall.iloc[0] if len(rsmall) else g.loc[g["score"].idxmax()]
        _qsz = qsize.get(_hit["query_abp"])
        n_used = int(_hit["n_match"])
        frac = n_used / _qsz if _qsz else None
        sn = pd.to_numeric(_hit.get("score_norm"), errors="coerce")
        _rmsd = pd.to_numeric(_hit.get("rmsd"), errors="coerce")
        _snv = float(sn) if pd.notna(sn) else None
        _rmv = float(_rmsd) if pd.notna(_rmsd) else None
        out[pair] = {
            # raw FoldDisco outputs (query -> target) + normalised versions
            "Matched residues": (f"{n_used}/{_qsz}" if _qsz else str(n_used)),  # n_match
            "% shared motif": (f"{round(frac * 100)}%" if frac is not None else "—"),
            "FoldDisco score": round(float(_hit["score"]), 1),                  # score brut
            "Norm. score": round(_snv, 2) if _snv is not None else None,        # score/self
            "RMSD (Å)": round(_rmv, 1) if _rmv is not None else None,           # rmsd
            "Interpretation": _reading(n_used, frac, _snv, _rmv),
        }
    return out


# ── DISCOVERY: interface motif (per ABP × cluster) searched in PDB + AlphaFold ─
# discovery CSV (script 14)  : db, target_id, target_chain, idfscore, rmsd, coverage…
# names CSV (script 14b)      : key, protein_name, organism  (UniProt / RCSB)
# We show the protein NAME (not the raw id), deduplicate by name, 2 tabs.

_DISCO_NAMES = "data/exports/abp_site_domain/folddisco_names.csv"
_DB_TABS = [("pdb", "PDB (real structures)"),
            ("afdb", "AlphaFold (predictions)")]

# Filter on the interpretation (same categories as _reading, the local FoldDisco).
_FILTERS = {
    "Same motif (strong) only": {"same motif (strong)"},
    "Same motif + shared (broad/partial)": {
        "same motif (strong)",
        "residues largely shared, loose superposition",
        "partially shared motif"},
    "All": None,
}
_INTERP_COL = {
    "same motif (strong)": "#0072B2",
    "residues largely shared, loose superposition": "#E69F00",
    "partially shared motif": "#E69F00",
    "different motifs": "#8c8c8c",
    "few residues — inconclusive": "#8c8c8c",
}


def _discovery_stamp():
    paths=[Path(_DISCO_CSV),Path(_DISCO_NAMES),Path(__file__).with_name('folddisco_audit.py')]
    return tuple((str(p),p.stat().st_mtime_ns,p.stat().st_size) for p in paths if p.exists())


@st.cache_data(show_spinner=False)
def _load_discovery(stamp):
    if not os.path.exists(_DISCO_CSV):
        return None
    df = pd.read_csv(_DISCO_CSV)
    # join resolved names (if available)
    if os.path.exists(_DISCO_NAMES):
        nm = pd.read_csv(_DISCO_NAMES)[["key", "protein_name", "organism"]]
        df["key"] = [t if d == "afdb" else f"{t}_{c}" for d, t, c
                     in zip(df["db"], df["target_id"],
                            df["target_chain"].fillna(""))]
        df = df.merge(nm.drop_duplicates('key'), on="key", how="left",validate='many_to_one')
    else:
        df["protein_name"] = None
        df["organism"] = None
    df["name"] = df["protein_name"].fillna("").replace("", pd.NA)
    df["name"] = df["name"].fillna(df["target_id"])      # fallback = raw id
    df = normalize_discovery(df)
    # graded interpretation (same rules as the local FoldDisco, see _reading)
    df["interpretation"] = [
        _reading(n, c, s, r) for n, c, s, r in
        zip(df["nodecount"], df["coverage"], df["score_norm"], df["rmsd"])]
    return df


def _hit_link(db, tid):
    return (f"https://www.rcsb.org/structure/{tid.upper()}" if db == "pdb"
            else f"https://alphafold.ebi.ac.uk/entry/{tid}")


def _dedup_by_name(sub):
    """One row per protein NAME (best score), sorted by descending score."""
    return sub.sort_values("idfscore", ascending=False).drop_duplicates("name")


def _interp_filter_ui(key):
    """Show all stored categories unless the reader selects a heuristic filter."""
    return st.radio("Keep only", list(_FILTERS), index=2, horizontal=True,
                    key=key)


def _hbar(names, scores, colors=None):
    """HORIZONTAL bar chart (full readable names), best on top."""
    fig = go.Figure(go.Bar(
        x=list(scores), y=list(names), orientation="h",
        marker_color=colors or "#3b6fb5"))
    fig.update_layout(
        height=max(220, 26 * len(names) + 60),
        margin=dict(l=6, r=6, t=6, b=6),
        xaxis_title="Score ratio (source-labelled or best-hit denominator)",
        yaxis=dict(autorange="reversed"))
    plotly_chart(fig, use_container_width=True)


def _render_db_table(sub, db, filt):
    """Table + chart for one db (sub already filtered db + non-source + names)."""
    d = sub.copy()
    keep = _FILTERS[filt]
    if keep is not None:
        d = d[d["interpretation"].isin(keep)]
    d = _dedup_by_name(d).copy()
    if d.empty:
        st.info("No FoldDisco hit matches this filter.")
        return
    d["Source"] = (d["target_id"].str.upper()
                   + (" / " + d["target_chain"].fillna("") if db == "pdb" else ""))
    d["Norm. score"] = d["score_norm"].round(2)
    d["RMSD (Å)"] = d["rmsd"].round(2)
    d["Coverage"] = (d["coverage"] * 100).round().astype("Int64").astype(str) + "%"
    d["Normalisation basis"]=d.normalization_basis
    d["Denominator"]=d.normalization_denominator
    cols = ["name", "organism", "interpretation", "Norm. score", "RMSD (Å)",
            "Coverage", "Normalisation basis", "Denominator", "Source"]
    try:
        from folddisco_annotations import annotate_hits
        d=annotate_hits(d)
        cols += ['go_molecular_function','go_biological_process','go_cellular_component','go_annotation_status']
        st.caption('GO uses a partial local UniProt cache joined by exact accession for AlphaFold hits. '
                   'Not fetched is different from no GO terms returned. PDB-to-UniProt correspondence is '
                   'unresolved here. Evidence codes and retrieval provenance are included in the CSV; '
                   'GO annotations do not independently validate an actin-binding domain.')
    except ImportError:
        st.caption('No local GO annotation cache is installed. Motif hits are not experimentally validated actin-binding domains.')
    show = d[cols].rename(columns={"name": "Protein", "organism": "Organism",
                                   "interpretation": "Interpretation"})
    st.dataframe(
        show, hide_index=True, use_container_width=True, height=400,
        column_config={
            "Protein": st.column_config.TextColumn(width="large"),
            "Organism": st.column_config.TextColumn(width="medium")})
    top = d.head(15)
    _hbar(top["name"], top["score_norm"],
          [_INTERP_COL.get(i, "#3b6fb5") for i in top["interpretation"]])
    st.download_button('Download displayed hits and annotation provenance (CSV)',d.to_csv(index=False).encode(),
                       file_name=f'folddisco_{db}_hits.csv',mime='text/csv',
                       key=f'fd_hits_{db}_{sub.query_abp.iloc[0]}_{sub.query_cluster.iloc[0]}')


@st.cache_data(show_spinner=False)
def _load_motif_catalog(stamp):
    if not all(p.exists() for p in CATALOG_FILES):
        return motif_catalog(pd.DataFrame(),pd.DataFrame())
    return motif_catalog(*(pd.read_csv(p,low_memory=False) for p in CATALOG_FILES))


@st.cache_data(show_spinner=False)
def _query_coordinates(path,chain,mtime):
    return read_chain_ca(Path(path),chain)


def _render_local_query(catalog,abp,cluster):
    selected=catalog[catalog.query_abp.eq(abp)&catalog.query_cluster.eq(cluster)]
    if selected.empty:
        st.info('No current local source-table motif is available for this saved result.');return
    row=selected.iloc[0].to_dict()
    from folddisco_jobs import combine_sites
    options = sorted(set(catalog.loc[catalog.query_abp.eq(abp), 'query_cluster']) - {cluster})
    extras = st.multiselect('Combine with other binding sites of this ABP', options,
                           key=f'fd_combination_{abp}_{cluster}') if options else []
    if extras:
        try:
            row = combine_sites(pd.read_csv(CATALOG_FILES[0]), pd.read_csv(CATALOG_FILES[1]), abp, [cluster, *extras])
        except ValueError as exc:
            st.info(str(exc)); return
    path=structure_path(row)
    st.caption('This motif is reconstructed from the current source tables using the best-resolution '
               'interaction for this ABP/site; combinations use one observed PDB chain containing every selected site. Historical result files did not retain the exact submitted '
               'positions or structure hash, so agreement with the historical query is not established. '
               'Positions below are PDB residue identifiers of the ABP chain, not P60709 actin positions.')
    st.write(f"Source: {row['source_pdb'].upper()} / chain {row['source_chain']} · "
             f"interaction {row['interaction_id']} · {row['reconstructed_size']} distinct contact positions")
    st.code(row['contact_positions'] or 'No contact positions in the current source tables')
    if row['unparsed_contact_positions']:
        st.warning('Unparsed source residue identifiers: '+row['unparsed_contact_positions'])
    if path is None:
        st.info('The corresponding structure is not present locally. Position validation and 3D preparation are unavailable.');return
    try:coords=_query_coordinates(str(path),row['source_chain'],path.stat().st_mtime_ns)
    except (ValueError,KeyError) as exc:
        st.warning(str(exc));return
    text=st.text_area('ABP query positions to prepare (comma-separated PDB residue identifiers)',
                      value=row['contact_positions'],key=f'fd_query_positions_{abp}_{row["query_cluster"]}',height=90)
    checked=validate_motif(text,coords.position,row['source_chain'])
    if checked['submitted_chain'] != row['source_chain']:
        st.caption(f"For FoldDisco export only, source chain {row['source_chain']} is named {checked['submitted_chain']}. Coordinates and residue numbers are unchanged. Download the matching prepared PDB with the motif.")
    for error in checked['errors']:st.warning(error)
    if checked['duplicate_tokens_removed']:st.caption('Repeated position tokens are counted once.')
    picked=coords[coords.position.isin(checked['positions'])]
    st.caption(f"Prepared motif: {len(checked['positions'])} residues; public server limit: 32. "
               "The initial selection uses ABP residues observed in contact with actin. Residues far apart in the sequence can lie next to one another in 3D.")
    from Bio.SeqUtils import seq1
    from html import escape
    selected_positions = set(checked['positions'])
    cells = []
    for residue in coords.itertuples():
        chosen = residue.position in selected_positions
        colour = '#E69F00' if chosen else '#F2F3F5'
        letter = seq1(residue.residue, custom_map={'HIC': 'H'})
        cells.append(f'<span title="{escape(str(residue.residue))} {escape(str(residue.position))}" '
                     f'style="display:inline-block;padding:3px;margin:1px;background:{colour};color:#222">'
                     f'{letter}<small style="display:block;font-size:9px">{escape(str(residue.position))}</small></span>')
    with st.expander('Resolved ABP sequence and selected motif'):
        st.caption('Orange residues form the prepared motif. Labels use PDB numbering; unresolved residues are omitted. Edit the position field above to change the selection.')
        st.markdown('<div style="font-family:monospace;line-height:1.2">'+''.join(cells)+'</div>', unsafe_allow_html=True)

    fig=go.Figure()
    fig.add_trace(go.Scatter3d(x=coords.x,y=coords.y,z=coords.z,mode='markers',name='Resolved C-alpha atoms',
                             marker=dict(color='#BBBBBB',size=3,opacity=.45),customdata=coords[['residue','position']],
                             hovertemplate='%{customdata[0]} %{customdata[1]}<extra></extra>'))
    fig.add_trace(go.Scatter3d(x=picked.x,y=picked.y,z=picked.z,mode='markers',name='Prepared motif',
                             marker=dict(color='#E69F00',size=6),customdata=picked[['residue','position']],
                             hovertemplate='%{customdata[0]} %{customdata[1]}<extra></extra>'))
    fig.update_layout(height=460,scene=dict(aspectmode='data',xaxis_visible=False,yaxis_visible=False,zaxis_visible=False),
                      margin=dict(l=0,r=0,t=0,b=0),legend=dict(orientation='h'))
    plotly_chart(fig,use_container_width=True,key=f'fd_query_3d_{abp}_{cluster}')
    st.caption('Local C-alpha representation: gray = resolved chain residues; orange = prepared motif. '
               'Editing this selection does not recalculate or change the saved discovery results below.')
    if not checked['errors']:
        with st.expander('Export prepared motif and coordinates'):
            st.download_button('Download prepared motif and structure fingerprint (JSON)',prepared_query_json(row,checked,path),
                               file_name='folddisco_prepared_motif.json',mime='application/json',key=f'fd_query_json_{abp}_{cluster}')
            st.download_button('Download prepared residue coordinates (CSV)',picked.to_csv(index=False).encode(),
                               file_name='folddisco_prepared_coordinates.csv',mime='text/csv',key=f'fd_query_csv_{abp}_{cluster}')
            if checked['text_export_supported']:
                from folddisco_jobs import chain_pdb_text
                st.code(checked['query'])
                st.download_button('Download matching prepared chain (PDB)',chain_pdb_text(path,row['source_chain']),
                                   file_name='folddisco_query.pdb',key=f'fd_query_pdb_{abp}_{cluster}')
                st.download_button('Download FoldDisco motif text',checked['query'],file_name='folddisco_motif.txt',
                                   mime='text/plain',key=f'fd_query_text_{abp}_{cluster}')
            else:
                st.info('Insertion codes and negative residue numbers are preserved in JSON, but are not supported by the FoldDisco query parser.')

    if not checked['errors'] and checked['query']:
        _render_query_jobs(row, checked, path)


def _render_query_jobs(row, checked, path):
    import json
    import hashlib
    from folddisco_jobs import JOBS, DATABASES, prepare, submit, refresh, result_table, chain_pdb_text, retry
    current_hash = hashlib.sha256(chain_pdb_text(path, row['source_chain']).encode()).hexdigest()
    matches = []
    for file in JOBS.glob('*/job.json'):
        try:
            record = json.loads(file.read_text())
        except (ValueError, OSError):
            continue
        if (record.get('motif') == checked['query']
                and record.get('databases') == DATABASES
                and record.get('structure_sha256') == current_hash):
            matches.append((file.parent, record))
    current = max(matches, key=lambda item: item[1]['created_utc']) if matches else None
    with st.expander('Run this motif or inspect its new results', expanded=current is not None):
        if Path('data/.slim_deploy').exists():
            st.caption('New searches run from the full research project. This public version displays saved results.')
        elif len(checked['positions']) > 32:
            st.info('The public FoldDisco server accepts at most 32 residues. Edit the motif or export it for a local search; the app does not truncate it automatically.')
        elif st.button('Search this motif in PDB and AlphaFold', key='fd_submit_motif',
                       disabled=current is not None and current[1]['state'] != 'prepared'):
            try:
                folder, record = prepare(row, ','.join(checked['positions']), path)
                record = submit(folder)
                current = folder, record
            except (ValueError, OSError) as exc:
                st.error(str(exc))
        if current is None:
            st.caption('No tracked search matches this selection yet. Editing a motif never changes historical results.')
            return
        folder, record = current
        source = record.get('source', {})
        if (source.get('query_abp'), source.get('query_cluster')) != (row['query_abp'], row['query_cluster']):
            st.caption(f"Reusing the exact same structure, motif and databases submitted for {source.get('query_abp')} / {source.get('query_cluster')}. The original provenance is retained.")
        if record['state'] in {'pending', 'results_pending'}:
            if st.button('Check search progress', key='fd_refresh_motif'):
                record = refresh(folder)
        if record['state'] in {'failed', 'submission_uncertain'} and not Path('data/.slim_deploy').exists():
            if st.button('Retry this search', key='fd_retry_motif'):
                record = retry(folder)
        st.write(record.get('message', record['state']))
        st.caption(f"State: {record['state']} · saved {record['updated_utc']} · exact submitted structure and motif retained.")
        if record['state'] == 'complete':
            frame = result_table(folder)
            if frame.empty:
                st.info('Search completed with no returned alignments.')
            else:
                st.dataframe(frame, hide_index=True, width='stretch')
                st.download_button('Download new search results', frame.to_csv(index=False).encode(),
                                   file_name='folddisco_new_results.csv', key='fd_fresh_csv')
            st.caption('These are the alignments returned by the service, which can limit the number of hits. They belong to the displayed submitted motif. They are separate from the historical search below; no homology or binding-function classification is inferred.')
        st.download_button('Download search provenance', json.dumps(record, indent=2),
                           file_name='folddisco_search.json', key='fd_fresh_manifest')


def _render_saved_searches(records, abp, site):
    """Results remain accessible even when the prepared motif is edited."""
    import json
    from folddisco_jobs import result_table
    from folddisco_status import search_label
    matching = [(p, r) for p, r in records if r.get('source', {}).get('query_abp') == abp
                and site in r.get('source', {}).get('query_cluster', '').split('+')]
    if not matching:
        return False
    # Prefer a usable result, retaining every old query for audit.
    matching.sort(key=lambda item: item[1].get('state') != 'complete')
    options = list(range(len(matching)))
    index = st.selectbox('Saved search', options, key=f'fd_saved_{abp}_{site}',
        format_func=lambda i: f"{matching[i][1].get('source',{}).get('query_cluster')} · {search_label(matching[i][1])} · {matching[i][1].get('updated_utc','')[:10]}") if len(options)>1 else 0
    folder, record = matching[index]
    st.markdown(f"**{search_label(record)}**")
    source = record.get('source', {})
    st.caption(f"Submitted source: {source.get('source_pdb','').upper()} / chain {source.get('source_chain')} · {len(record.get('positions',[]))} residues. Editing the preparation below does not change these saved results.")
    if record.get('state') == 'complete':
        try:
            frame = result_table(folder)
        except (OSError, ValueError, KeyError) as exc:
            st.error(f'Saved result cannot be read: {exc}'); return True
        if frame.empty:
            st.info('Search completed with no returned alignments. This does not prove the motif or an actin-binding protein is absent from nature.')
        else:
            if 'idfscore' in frame:
                frame=frame.sort_values('idfscore',ascending=False)
            from folddisco_annotations import annotate_hits
            frame=annotate_hits(frame)
            visible = [c for c in ['database','target_id','Record','nodecount','coverage','idfscore','rmsd','targetresidues',
                                   'go_molecular_function','go_biological_process','go_cellular_component','go_annotation_status'] if c in frame]
            st.dataframe(frame[visible],hide_index=True,width='stretch',height=400,
                         column_config={'Record':st.column_config.LinkColumn('Structure record',display_text='Open')})
            st.download_button('Download saved search results (CSV)',frame.to_csv(index=False).encode(),
                file_name='folddisco_saved_results.csv',key=f'fd_saved_csv_{abp}_{site}')
            st.caption('Coverage = matched residues / submitted motif size. RMSD is in Å. Hits are structural candidates; the service may cap the returned list.')
            st.caption('GO annotations use the existing partial UniProt cache by exact accession. Missing annotations are shown explicitly; names and PDB-to-UniProt mappings are not guessed.')
    else:
        st.info(record.get('message',search_label(record)))
    st.download_button('Download saved search provenance (JSON)',json.dumps(record,indent=2),
                       file_name='folddisco_saved_search.json',key=f'fd_saved_manifest_{abp}_{site}')
    return True


@st.cache_data(show_spinner=False)
def _local_control_tables(stamp):
    root=Path('data/exports/folddisco_controls')
    return tuple(pd.read_csv(root/name) for name in ['queries.csv','hits.csv','shared_site_controls.csv'])


def _render_local_controls(abp, site):
    root=Path('data/exports/folddisco_controls')
    paths=[root/n for n in ['queries.csv','hits.csv','shared_site_controls.csv']]
    if not all(p.exists() for p in paths):return
    queries,hits,controls=_local_control_tables(tuple((p.stat().st_mtime_ns,p.stat().st_size) for p in paths))
    selected=queries[queries.query_abp.eq(abp)&queries.query_cluster.eq(site)]
    if selected.empty:return
    with st.expander('Local validation: known ABPs and observed actin contacts'):
        st.info('This separate local search tests the motif against representative ABP chains already in this dataset. It also accepts motifs longer than 32 residues. It does not search the full PDB or AlphaFold databases.')
        st.caption('A structural match is compared with the target chain’s recorded actin-contact residues. The same-site comparison tests contacts with the selected actin site; the any-site comparison includes all recorded actin contacts of that target chain. These are observed contact sets, not curated boundaries of every actin-binding domain.')
        st.dataframe(selected,hide_index=True,width='stretch')
        if selected.iloc[0]['state']!='complete':return
        self_cov=float(selected.iloc[0]['self_coverage'])
        if self_cov<.999:
            st.warning(f'The highest-scoring self-match covers only {self_cov:.0%} of this query. Interpret partial matches cautiously; this control does not establish sensitivity or specificity.')
        comparison=controls[controls.query_abp.eq(abp)&controls.query_cluster.eq(site)]
        if not comparison.empty:
            st.markdown('**Known partners sharing this actin site**')
            st.dataframe(comparison.drop(columns=['query_abp','query_cluster']),hide_index=True,width='stretch')
        else:
            st.caption('No other ABP in the local representative panel is recorded at this same actin site.')
        sub=hits[hits.query_abp.eq(abp)&hits.query_cluster.eq(site)].sort_values('idfscore',ascending=False)
        columns=[c for c in ['target_abp','target_pdb','target_chain','matched_residues','coverage','rmsd_A',
                            'matched_contact_count_same_site','fraction_matched_on_observed_contacts',
                            'matched_contact_count_any_site','fraction_matched_on_any_observed_contact'] if c in sub]
        st.markdown('**Best saved match per target chain**')
        st.dataframe(sub[columns],hide_index=True,width='stretch',height=350)
        st.caption('Default FoldDisco parameters; highest IDF match per target chain. A hit outside the recorded contacts does not validate a shared actin-binding motif. No negative-control specificity estimate or evolutionary-homology claim is made.')
        st.download_button('Download local matches and contact checks',sub.to_csv(index=False).encode(),
                           file_name=f'folddisco_local_{site}.csv',key=f'fd_local_csv_{abp}_{site}')
        st.download_button('Download all known-partner controls',controls.to_csv(index=False).encode(),
                           file_name='folddisco_shared_site_controls.csv',key=f'fd_controls_csv_{abp}_{site}')
        st.download_button('Download local-search methods and provenance',(root/'manifest.json').read_bytes(),
                           file_name='folddisco_local_manifest.json',key=f'fd_local_manifest_{abp}_{site}')


def render_discovery(sel_abp):
    """Per-ABP view, broken down by cluster: one motif per site, 2 dbs (PDB/AFDB)."""
    st.markdown("#### Discovery — interface motif per cluster (FoldDisco)")
    st.info("FoldDisco searches for similar arrangements of amino acids in 3D. Here the query is an observed ABP contact motif. A match is a structural candidate, not evidence that the hit binds actin or has the same function.")
    with st.expander("How FoldDisco scores are interpreted"):
        st.markdown("Coverage is the fraction of stored query residues matched. For each ABP/site/database, "
                    "the score is divided by the highest positive source-labelled hit, or by the best available "
                    "hit when no source-labelled hit exists. The basis and numerical denominator are shown "
                    "in the table. The legacy source label identifies the same PDB entry (not necessarily "
                    "the same chain) or the source UniProt accession; it is not a verified geometric self-match. "
                    "Ratios can exceed 1 and are not probabilities or comparable calibrated qualities. "
                    "A best-hit ratio of 1 only identifies the best saved hit for that query. RMSD (Å) describes "
                    "the deviation of matched residues after superposition.")
        st.markdown("The current app uses exploratory thresholds: fewer than 5 matched residues "
                    "is inconclusive; at least 75% coverage, RMSD ≤ 4 Å and normalised score "
                    "≥ 0.15 gives the ‘strong’ category. Other hits with at least 75% coverage "
                    "are grouped as broadly shared, and 50–75% as partially shared. These "
                    "categories do not establish homology, actin binding or biological function.")
        st.caption("All categories are shown by default. The chart shows the first 15 hits "
                   "after filtering and deduplication by protein name; the table contains all "
                   "retained names. Inspect source identifiers for specific structures. The local pairwise "
                   "script13 instead divides by its saved exact query-to-itself score. The search hypotheses "
                   "shown here have not been independently validated as actin-binding domains.")
    df = _load_discovery(_discovery_stamp())
    sources=[*CATALOG_FILES,Path(__file__).with_name('folddisco_audit.py')]
    stamp=tuple((str(p),p.stat().st_mtime_ns,p.stat().st_size) for p in sources if p.exists())
    catalog=_load_motif_catalog(stamp)
    discovery=df if df is not None else pd.DataFrame()
    from folddisco_jobs import JOBS
    from folddisco_status import saved_searches, status_inventory
    records=saved_searches(JOBS)
    inventory=status_inventory(catalog,discovery,records)
    local_queries=Path('data/exports/folddisco_controls/queries.csv')
    if local_queries.exists():
        local_status=pd.read_csv(local_queries)[['query_abp','query_cluster','state']].rename(
            columns={'query_abp':'ABP','query_cluster':'Site','state':'Local known-ABP control'})
        inventory=inventory.merge(local_status,on=['ABP','Site'],how='left',validate='one_to_one')
    with st.expander('Search status for every ABP and site'):
        st.dataframe(inventory,hide_index=True,width='stretch')
        st.caption('Historical rows have incomplete query provenance. Tracked searches retain the exact motif and coordinates. Invalid old queries are excluded from negative-search counts.')
        st.download_button('Download all search statuses',inventory.to_csv(index=False).encode(),
                           file_name='folddisco_search_status.csv',key='fd_all_status')
    local=_load_folddisco(os.path.getmtime(_FD_CSV) if os.path.exists(_FD_CSV) else 0)
    with st.expander('Dataset coverage: ABPs, local motifs and saved results'):
        from folddisco_jobs import JOBS
        ledger = []
        for _, item in records:
            source = item.get('source', {})
            ledger.append({'ABP': source.get('query_abp'), 'Sites': source.get('query_cluster'),
                           'State': item.get('state'), 'Returned alignments': item.get('hit_rows'),
                           'Updated': item.get('updated_utc')})
        if ledger:
            st.markdown('**Tracked searches with exact query provenance**')
            st.dataframe(pd.DataFrame(ledger), hide_index=True, width='stretch')
            st.caption('A complete search with zero returned alignments is distinct from a missing or failed search. The historical inventory below describes the original result files only.')
        coverage,details=coverage_tables(catalog,discovery,local if local is not None else pd.DataFrame())
        if coverage.empty:
            st.info('No local motif source tables or saved FoldDisco queries are present.')
        else:
            st.dataframe(coverage,hide_index=True,width='stretch')
            st.caption('Counts describe files present in this dataset. A missing result row does not distinguish '
                       'an unrun search, a failed search or a completed search with no hits. Saved hits are truncated '
                       'by the pipeline to its per-database limit; they are not an exhaustive search inventory. '
                       'Current motifs are reconstructed, and exact historical query provenance is unavailable.')
            st.download_button('Download FoldDisco coverage by ABP',coverage.to_csv(index=False).encode(),
                               file_name='folddisco_abp_coverage.csv',mime='text/csv',key=f'fd_coverage_{sel_abp}')
            st.dataframe(details[details.query_abp.eq(sel_abp)],hide_index=True,width='stretch')
            st.download_button('Download motif/source/result inventory',details.to_csv(index=False).encode(),
                               file_name='folddisco_motif_inventory.csv',mime='text/csv',key=f'fd_inventory_{sel_abp}')
    abp = df[df["query_abp"] == sel_abp] if df is not None else pd.DataFrame(columns=['query_cluster'])
    clusters=sorted(set(abp.query_cluster.dropna())|set(catalog.loc[catalog.query_abp.eq(sel_abp),'query_cluster'].dropna()))
    if not clusters:
        st.info('No current local motif or saved discovery result for this ABP.');return
    cl = st.selectbox(
        f"Actin site of {sel_abp} ({len(clusters)} cluster(s) → as many motifs)",
        clusters, key=f"disco_cl_{sel_abp}")
    st.subheader('Saved results')
    tracked=_render_saved_searches(records,sel_abp,cl)
    if not abp.empty and abp.query_cluster.eq(cl).any():
        with st.expander('Historical results for the original single-site search',expanded=not tracked):
            filt = _interp_filter_ui(f"disco_filt_{sel_abp}_{cl}")
            sub = abp[(abp["query_cluster"] == cl) & (~abp["is_source"])]
            tabs = st.tabs([lbl for _, lbl in _DB_TABS])
            for tab, (db, _) in zip(tabs, _DB_TABS):
                with tab:
                    _render_db_table(sub[sub["db"] == db], db, filt)
    elif not tracked:
        st.info('No saved search for this ABP/site yet. Prepare and submit a motif below; an empty inventory is not a failed search.')
    _render_local_controls(sel_abp,cl)
    with st.expander('Prepare or edit a new motif',expanded=False):
        _render_local_query(catalog,sel_abp,cl)


def render_discovery_cluster(cluster_id):
    """Per-CLUSTER view — pools the discoveries of ALL the site's ABPs,
    deduplicated by name. Query counts are not biological validation."""
    st.markdown("**Discovery — proteins matching this site's motif (FoldDisco)**")
    df = _load_discovery(_discovery_stamp())
    if df is None:
        return
    base = df[(df["query_cluster"] == cluster_id) & (~df["is_source"])]
    if base.empty:
        return
    filt = _interp_filter_ui(f"disco_clfilt_{cluster_id}")
    keep = _FILTERS[filt]
    tabs = st.tabs([lbl for _, lbl in _DB_TABS])
    for tab, (db, _) in zip(tabs, _DB_TABS):
        with tab:
            sub = base[base["db"] == db]
            if keep is not None:
                sub = sub[sub["interpretation"].isin(keep)]
            if sub.empty:
                continue
            rows = []
            for nom, g in sub.groupby("name"):
                best = g.loc[g["idfscore"].idxmax()]
                rows.append({
                    "Protein": nom,
                    "Organism": best.get("organism", ""),
                    "Interpretation": best["interpretation"],
                    "Found via (ABP)": ", ".join(sorted(g["query_abp"].unique())),
                    "# ABPs": g["query_abp"].nunique(),
                    "Norm. score": round(float(best["score_norm"]), 2),
                    "Normalisation basis": best['normalization_basis'],
                    "Denominator": best['normalization_denominator'],
                    "RMSD (Å)": round(float(best["rmsd"]), 2),
                    "Link": _hit_link(db, best["target_id"]),
                    "db": db,"target_id": best['target_id'],"target_chain": best['target_chain'],
                })
            out = pd.DataFrame(rows).sort_values(
                ["# ABPs", "Norm. score"], ascending=[False, False])
            try:
                from folddisco_annotations import annotate_hits
                out=annotate_hits(out)
            except ImportError:
                pass
            st.dataframe(
                out.drop(columns=['db','target_id','target_chain']), hide_index=True, use_container_width=True, height=400,
                column_config={
                    "Protein": st.column_config.TextColumn(width="large"),
                    "Link": st.column_config.LinkColumn("Record",
                                                        display_text="open")})
            st.download_button('Download pooled hits with score and annotation provenance',out.to_csv(index=False).encode(),
                               file_name=f'folddisco_{cluster_id}_{db}.csv',mime='text/csv',key=f'fd_cluster_csv_{cluster_id}_{db}')
